// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt8aA85tQfwBhGTd_zakdvqZ-DfHs0iCQ',
    appId: '1:551913295878:web:b71fe9cc021b10ac567387',
    messagingSenderId: '551913295878',
    projectId: 'prosignal-97cb6',
    authDomain: 'prosignal-97cb6.firebaseapp.com',
    storageBucket: 'prosignal-97cb6.appspot.com',
    measurementId: 'G-2XJD954GBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOhs5VeSJQ-6q2CSShkYaX9_OP_dBtKg',
    appId: '1:551913295878:android:f903c51b2836c42c567387',
    messagingSenderId: '551913295878',
    projectId: 'prosignal-97cb6',
    storageBucket: 'prosignal-97cb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwxGHaqenWUkCsguzZN6YIQ9ymJRQMSB4',
    appId: '1:551913295878:ios:13389a5ecb8a6f25567387',
    messagingSenderId: '551913295878',
    projectId: 'prosignal-97cb6',
    storageBucket: 'prosignal-97cb6.appspot.com',
    iosBundleId: 'com.example.prosignal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwxGHaqenWUkCsguzZN6YIQ9ymJRQMSB4',
    appId: '1:551913295878:ios:ec15c93832b9d33d567387',
    messagingSenderId: '551913295878',
    projectId: 'prosignal-97cb6',
    storageBucket: 'prosignal-97cb6.appspot.com',
    iosBundleId: 'com.example.prosignal.RunnerTests',
  );
}
